mysql:
  image: mysql/mysql-server
  ports:
    - "3306:3306"
  environment:
    - MYSQL_USER=root
    - MYSQL_PASSWORD=dozement1994
    - MYSQL_DATABASE=commerce
    - MYSQL_RANDOM_ROOT_PASSWORD=false
  volumes:
    - "./conf.d:/etc/mysql/conf.d:ro"